//! The animal catalogue: dedicated picture APIs first, then dog.ceo breeds, then Wikimedia
//! Commons categories (species by scientific name, or a curated "Quality images of …" category
//! where the species category itself holds few photos). Every Commons category was checked when
//! added: most hold 50 or more bitmap photos, a few rarer animals (shoebill, walrus) hold 4–9.

use super::{Animal, Source};

pub static CATALOG: &[Animal] = &[
    Animal {
        name: "capybara",
        aliases: &["capy"],
        emoji: "🦫",
        source: Source::CapyLol,
    },
    Animal {
        name: "fox",
        aliases: &["red fox"],
        emoji: "🦊",
        source: Source::RandomFox,
    },
    Animal {
        name: "dog",
        aliases: &["doggo", "puppy", "pupper"],
        emoji: "🐶",
        source: Source::RandomDog,
    },
    Animal {
        name: "cat",
        aliases: &["kitty", "kitten"],
        emoji: "🐱",
        source: Source::TheCatApi,
    },
    Animal {
        name: "duck",
        aliases: &[],
        emoji: "🦆",
        source: Source::RandomDuck,
    },
    Animal {
        name: "bunny",
        aliases: &["rabbit"],
        emoji: "🐰",
        source: Source::Bunnies,
    },
    Animal {
        name: "pug",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("pug"),
    },
    Animal {
        name: "corgi",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("pembroke"),
    },
    Animal {
        name: "shiba",
        aliases: &["shiba inu"],
        emoji: "🐶",
        source: Source::DogBreed("shiba"),
    },
    Animal {
        name: "husky",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("husky"),
    },
    Animal {
        name: "beagle",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("beagle"),
    },
    Animal {
        name: "labrador",
        aliases: &["lab"],
        emoji: "🐶",
        source: Source::DogBreed("labrador"),
    },
    Animal {
        name: "poodle",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("poodle"),
    },
    Animal {
        name: "dachshund",
        aliases: &["sausage dog"],
        emoji: "🐶",
        source: Source::DogBreed("dachshund"),
    },
    Animal {
        name: "samoyed",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("samoyed"),
    },
    Animal {
        name: "golden retriever",
        aliases: &["golden"],
        emoji: "🐶",
        source: Source::DogBreed("retriever/golden"),
    },
    Animal {
        name: "pomeranian",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("pomeranian"),
    },
    Animal {
        name: "chihuahua",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("chihuahua"),
    },
    Animal {
        name: "border collie",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("collie/border"),
    },
    Animal {
        name: "dalmatian",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("dalmatian"),
    },
    Animal {
        name: "greyhound",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("greyhound"),
    },
    Animal {
        name: "akita",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("akita"),
    },
    Animal {
        name: "malamute",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("malamute"),
    },
    Animal {
        name: "newfoundland",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("newfoundland"),
    },
    Animal {
        name: "french bulldog",
        aliases: &["frenchie"],
        emoji: "🐶",
        source: Source::DogBreed("bulldog/french"),
    },
    Animal {
        name: "bulldog",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("bulldog/english"),
    },
    Animal {
        name: "boxer",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("boxer"),
    },
    Animal {
        name: "doberman",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("doberman"),
    },
    Animal {
        name: "schnauzer",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("schnauzer"),
    },
    Animal {
        name: "sheltie",
        aliases: &["shetland sheepdog"],
        emoji: "🐶",
        source: Source::DogBreed("sheepdog/shetland"),
    },
    Animal {
        name: "cocker spaniel",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("spaniel/cocker"),
    },
    Animal {
        name: "whippet",
        aliases: &[],
        emoji: "🐶",
        source: Source::DogBreed("whippet"),
    },
    Animal {
        name: "st bernard",
        aliases: &["saint bernard"],
        emoji: "🐶",
        source: Source::DogBreed("stbernard"),
    },
    Animal {
        name: "quokka",
        aliases: &[],
        emoji: "🦘",
        source: Source::Commons("Setonix brachyurus"),
    },
    Animal {
        name: "axolotl",
        aliases: &[],
        emoji: "🦎",
        source: Source::Commons("Ambystoma mexicanum"),
    },
    Animal {
        name: "sea otter",
        aliases: &[],
        emoji: "🦦",
        source: Source::Commons("Enhydra lutris"),
    },
    Animal {
        name: "otter",
        aliases: &[],
        emoji: "🦦",
        source: Source::Commons("Lutra lutra"),
    },
    Animal {
        name: "hedgehog",
        aliases: &[],
        emoji: "🦔",
        source: Source::Commons("Erinaceus europaeus"),
    },
    Animal {
        name: "red panda",
        aliases: &[],
        emoji: "🐼",
        source: Source::Commons("Ailurus fulgens"),
    },
    Animal {
        name: "panda",
        aliases: &["giant panda"],
        emoji: "🐼",
        source: Source::Commons("Ailuropoda melanoleuca"),
    },
    Animal {
        name: "sloth",
        aliases: &[],
        emoji: "🦥",
        source: Source::Commons("Bradypus variegatus"),
    },
    Animal {
        name: "koala",
        aliases: &[],
        emoji: "🐨",
        source: Source::Commons("Phascolarctos cinereus"),
    },
    Animal {
        name: "kangaroo",
        aliases: &[],
        emoji: "🦘",
        source: Source::Commons("Macropus giganteus"),
    },
    Animal {
        name: "wombat",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Vombatus ursinus"),
    },
    Animal {
        name: "platypus",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Ornithorhynchus anatinus"),
    },
    Animal {
        name: "penguin",
        aliases: &[],
        emoji: "🐧",
        source: Source::Commons("Aptenodytes forsteri"),
    },
    Animal {
        name: "owl",
        aliases: &["barn owl"],
        emoji: "🦉",
        source: Source::Commons("Tyto alba"),
    },
    Animal {
        name: "snowy owl",
        aliases: &[],
        emoji: "🦉",
        source: Source::Commons("Bubo scandiacus"),
    },
    Animal {
        name: "raccoon",
        aliases: &[],
        emoji: "🦝",
        source: Source::Commons("Procyon lotor"),
    },
    Animal {
        name: "red squirrel",
        aliases: &[],
        emoji: "🐿️",
        source: Source::Commons("Sciurus vulgaris"),
    },
    Animal {
        name: "squirrel",
        aliases: &[],
        emoji: "🐿️",
        source: Source::Commons("Sciurus carolinensis"),
    },
    Animal {
        name: "badger",
        aliases: &[],
        emoji: "🦡",
        source: Source::Commons("Meles meles"),
    },
    Animal {
        name: "ferret",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Mustela putorius furo"),
    },
    Animal {
        name: "meerkat",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Suricata suricatta"),
    },
    Animal {
        name: "lemur",
        aliases: &[],
        emoji: "🐒",
        source: Source::Commons("Lemur catta"),
    },
    Animal {
        name: "giraffe",
        aliases: &[],
        emoji: "🦒",
        source: Source::Commons("Giraffa camelopardalis"),
    },
    Animal {
        name: "elephant",
        aliases: &[],
        emoji: "🐘",
        source: Source::Commons("Loxodonta africana"),
    },
    Animal {
        name: "lion",
        aliases: &[],
        emoji: "🦁",
        source: Source::Commons("Panthera leo"),
    },
    Animal {
        name: "tiger",
        aliases: &[],
        emoji: "🐯",
        source: Source::Commons("Panthera tigris"),
    },
    Animal {
        name: "leopard",
        aliases: &[],
        emoji: "🐆",
        source: Source::Commons("Featured pictures of Panthera pardus"),
    },
    Animal {
        name: "cheetah",
        aliases: &[],
        emoji: "🐆",
        source: Source::Commons("Acinonyx jubatus"),
    },
    Animal {
        name: "snow leopard",
        aliases: &[],
        emoji: "🐆",
        source: Source::Commons("Panthera uncia"),
    },
    Animal {
        name: "lynx",
        aliases: &[],
        emoji: "🐈",
        source: Source::Commons("Quality images of Lynx lynx"),
    },
    Animal {
        name: "wolf",
        aliases: &[],
        emoji: "🐺",
        source: Source::Commons("Canis lupus"),
    },
    Animal {
        name: "bear",
        aliases: &["brown bear"],
        emoji: "🐻",
        source: Source::Commons("Ursus arctos"),
    },
    Animal {
        name: "polar bear",
        aliases: &[],
        emoji: "🐻‍❄️",
        source: Source::Commons("Ursus maritimus"),
    },
    Animal {
        name: "moose",
        aliases: &["elk"],
        emoji: "🫎",
        source: Source::Commons("Alces alces"),
    },
    Animal {
        name: "deer",
        aliases: &[],
        emoji: "🦌",
        source: Source::Commons("Cervus elaphus"),
    },
    Animal {
        name: "reindeer",
        aliases: &[],
        emoji: "🦌",
        source: Source::Commons("Rangifer tarandus"),
    },
    Animal {
        name: "bison",
        aliases: &[],
        emoji: "🦬",
        source: Source::Commons("Bison bison"),
    },
    Animal {
        name: "horse",
        aliases: &["pony"],
        emoji: "🐴",
        source: Source::Commons("Quality images of horses"),
    },
    Animal {
        name: "donkey",
        aliases: &[],
        emoji: "🫏",
        source: Source::Commons("Equus asinus"),
    },
    Animal {
        name: "zebra",
        aliases: &[],
        emoji: "🦓",
        source: Source::Commons("Equus quagga"),
    },
    Animal {
        name: "cow",
        aliases: &[],
        emoji: "🐄",
        source: Source::Commons("Bos taurus"),
    },
    Animal {
        name: "highland cow",
        aliases: &[],
        emoji: "🐂",
        source: Source::Commons("Highland cattle"),
    },
    Animal {
        name: "pig",
        aliases: &["piglet"],
        emoji: "🐷",
        source: Source::Commons("Sus scrofa domesticus"),
    },
    Animal {
        name: "sheep",
        aliases: &["lamb"],
        emoji: "🐑",
        source: Source::Commons("Ovis aries"),
    },
    Animal {
        name: "goat",
        aliases: &[],
        emoji: "🐐",
        source: Source::Commons("Capra aegagrus hircus"),
    },
    Animal {
        name: "alpaca",
        aliases: &[],
        emoji: "🦙",
        source: Source::Commons("Vicugna pacos"),
    },
    Animal {
        name: "llama",
        aliases: &[],
        emoji: "🦙",
        source: Source::Commons("Lama glama"),
    },
    Animal {
        name: "camel",
        aliases: &[],
        emoji: "🐪",
        source: Source::Commons("Camelus dromedarius"),
    },
    Animal {
        name: "hippo",
        aliases: &["hippopotamus"],
        emoji: "🦛",
        source: Source::Commons("Hippopotamus amphibius"),
    },
    Animal {
        name: "rhino",
        aliases: &["rhinoceros"],
        emoji: "🦏",
        source: Source::Commons("Ceratotherium simum"),
    },
    Animal {
        name: "gorilla",
        aliases: &[],
        emoji: "🦍",
        source: Source::Commons("Gorilla gorilla"),
    },
    Animal {
        name: "orangutan",
        aliases: &[],
        emoji: "🦧",
        source: Source::Commons("Pongo pygmaeus"),
    },
    Animal {
        name: "chimpanzee",
        aliases: &["chimp"],
        emoji: "🐒",
        source: Source::Commons("Pan troglodytes"),
    },
    Animal {
        name: "snow monkey",
        aliases: &["monkey"],
        emoji: "🐒",
        source: Source::Commons("Macaca fuscata"),
    },
    Animal {
        name: "hamster",
        aliases: &[],
        emoji: "🐹",
        source: Source::Commons("Mesocricetus auratus"),
    },
    Animal {
        name: "guinea pig",
        aliases: &[],
        emoji: "🐹",
        source: Source::Commons("Cavia porcellus"),
    },
    Animal {
        name: "mouse",
        aliases: &[],
        emoji: "🐭",
        source: Source::Commons("Mus musculus"),
    },
    Animal {
        name: "rat",
        aliases: &[],
        emoji: "🐀",
        source: Source::Commons("Rattus norvegicus"),
    },
    Animal {
        name: "chinchilla",
        aliases: &[],
        emoji: "🐭",
        source: Source::Commons("Chinchilla lanigera"),
    },
    Animal {
        name: "bat",
        aliases: &["fruit bat"],
        emoji: "🦇",
        source: Source::Commons("Pteropus poliocephalus"),
    },
    Animal {
        name: "mole",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Talpa europaea"),
    },
    Animal {
        name: "beaver",
        aliases: &[],
        emoji: "🦫",
        source: Source::Commons("Castor canadensis"),
    },
    Animal {
        name: "armadillo",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Dasypus novemcinctus"),
    },
    Animal {
        name: "anteater",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Myrmecophaga tridactyla"),
    },
    Animal {
        name: "pangolin",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Manis javanica"),
    },
    Animal {
        name: "tapir",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Tapirus terrestris"),
    },
    Animal {
        name: "okapi",
        aliases: &[],
        emoji: "🦓",
        source: Source::Commons("Okapia johnstoni"),
    },
    Animal {
        name: "aardvark",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Orycteropus afer"),
    },
    Animal {
        name: "fennec",
        aliases: &["fennec fox"],
        emoji: "🦊",
        source: Source::Commons("Vulpes zerda"),
    },
    Animal {
        name: "arctic fox",
        aliases: &[],
        emoji: "🦊",
        source: Source::Commons("Quality images of Vulpes lagopus"),
    },
    Animal {
        name: "seal",
        aliases: &[],
        emoji: "🦭",
        source: Source::Commons("Quality images of Phoca vitulina"),
    },
    Animal {
        name: "sea lion",
        aliases: &[],
        emoji: "🦭",
        source: Source::Commons("Zalophus californianus"),
    },
    Animal {
        name: "walrus",
        aliases: &[],
        emoji: "🦭",
        source: Source::Commons("Quality images of Odobenus rosmarus"),
    },
    Animal {
        name: "dolphin",
        aliases: &[],
        emoji: "🐬",
        source: Source::Commons("Tursiops truncatus"),
    },
    Animal {
        name: "whale",
        aliases: &["humpback"],
        emoji: "🐋",
        source: Source::Commons("Megaptera novaeangliae"),
    },
    Animal {
        name: "orca",
        aliases: &["killer whale"],
        emoji: "🐋",
        source: Source::Commons("Orcinus orca"),
    },
    Animal {
        name: "shark",
        aliases: &[],
        emoji: "🦈",
        source: Source::Commons("Carcharodon carcharias"),
    },
    Animal {
        name: "octopus",
        aliases: &[],
        emoji: "🐙",
        source: Source::Commons("Octopus vulgaris"),
    },
    Animal {
        name: "jellyfish",
        aliases: &[],
        emoji: "🪼",
        source: Source::Commons("Aurelia aurita"),
    },
    Animal {
        name: "turtle",
        aliases: &["sea turtle"],
        emoji: "🐢",
        source: Source::Commons("Chelonia mydas"),
    },
    Animal {
        name: "tortoise",
        aliases: &[],
        emoji: "🐢",
        source: Source::Commons("Testudo hermanni"),
    },
    Animal {
        name: "frog",
        aliases: &[],
        emoji: "🐸",
        source: Source::Commons("Rana temporaria"),
    },
    Animal {
        name: "tree frog",
        aliases: &[],
        emoji: "🐸",
        source: Source::Commons("Agalychnis callidryas"),
    },
    Animal {
        name: "gecko",
        aliases: &["leopard gecko"],
        emoji: "🦎",
        source: Source::Commons("Eublepharis macularius"),
    },
    Animal {
        name: "chameleon",
        aliases: &[],
        emoji: "🦎",
        source: Source::Commons("Chamaeleo calyptratus"),
    },
    Animal {
        name: "iguana",
        aliases: &[],
        emoji: "🦎",
        source: Source::Commons("Iguana iguana"),
    },
    Animal {
        name: "snake",
        aliases: &["python"],
        emoji: "🐍",
        source: Source::Commons("Python regius"),
    },
    Animal {
        name: "crocodile",
        aliases: &[],
        emoji: "🐊",
        source: Source::Commons("Crocodylus niloticus"),
    },
    Animal {
        name: "alligator",
        aliases: &[],
        emoji: "🐊",
        source: Source::Commons("Alligator mississippiensis"),
    },
    Animal {
        name: "parrot",
        aliases: &["macaw"],
        emoji: "🦜",
        source: Source::Commons("Ara macao"),
    },
    Animal {
        name: "cockatoo",
        aliases: &[],
        emoji: "🦜",
        source: Source::Commons("Cacatua galerita"),
    },
    Animal {
        name: "budgie",
        aliases: &["budgerigar"],
        emoji: "🦜",
        source: Source::Commons("Melopsittacus undulatus"),
    },
    Animal {
        name: "flamingo",
        aliases: &[],
        emoji: "🦩",
        source: Source::Commons("Phoenicopterus roseus"),
    },
    Animal {
        name: "peacock",
        aliases: &["peafowl"],
        emoji: "🦚",
        source: Source::Commons("Pavo cristatus"),
    },
    Animal {
        name: "swan",
        aliases: &[],
        emoji: "🦢",
        source: Source::Commons("Cygnus olor"),
    },
    Animal {
        name: "goose",
        aliases: &[],
        emoji: "🪿",
        source: Source::Commons("Branta canadensis"),
    },
    Animal {
        name: "puffin",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Fratercula arctica"),
    },
    Animal {
        name: "pelican",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Pelecanus onocrotalus"),
    },
    Animal {
        name: "toucan",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Ramphastos toco"),
    },
    Animal {
        name: "hummingbird",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Archilochus colubris"),
    },
    Animal {
        name: "robin",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Erithacus rubecula"),
    },
    Animal {
        name: "crow",
        aliases: &[],
        emoji: "🐦‍⬛",
        source: Source::Commons("Corvus corone"),
    },
    Animal {
        name: "raven",
        aliases: &[],
        emoji: "🐦‍⬛",
        source: Source::Commons("Corvus corax"),
    },
    Animal {
        name: "magpie",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Pica pica"),
    },
    Animal {
        name: "pigeon",
        aliases: &[],
        emoji: "🕊️",
        source: Source::Commons("Columba livia"),
    },
    Animal {
        name: "chicken",
        aliases: &["hen"],
        emoji: "🐔",
        source: Source::Commons("Quality images of chickens"),
    },
    Animal {
        name: "eagle",
        aliases: &["bald eagle"],
        emoji: "🦅",
        source: Source::Commons("Haliaeetus leucocephalus"),
    },
    Animal {
        name: "kiwi",
        aliases: &[],
        emoji: "🥝",
        source: Source::Commons("Apteryx mantelli"),
    },
    Animal {
        name: "ostrich",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Struthio camelus"),
    },
    Animal {
        name: "emu",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Dromaius novaehollandiae"),
    },
    Animal {
        name: "shoebill",
        aliases: &[],
        emoji: "🐦",
        source: Source::Commons("Balaeniceps rex"),
    },
    Animal {
        name: "bee",
        aliases: &[],
        emoji: "🐝",
        source: Source::Commons("Apis mellifera"),
    },
    Animal {
        name: "butterfly",
        aliases: &[],
        emoji: "🦋",
        source: Source::Commons("Vanessa atalanta"),
    },
    Animal {
        name: "ladybug",
        aliases: &["ladybird"],
        emoji: "🐞",
        source: Source::Commons("Coccinella septempunctata"),
    },
    Animal {
        name: "snail",
        aliases: &[],
        emoji: "🐌",
        source: Source::Commons("Helix pomatia"),
    },
    Animal {
        name: "crab",
        aliases: &[],
        emoji: "🦀",
        source: Source::Commons("Carcinus maenas"),
    },
    Animal {
        name: "lobster",
        aliases: &[],
        emoji: "🦞",
        source: Source::Commons("Homarus gammarus"),
    },
    Animal {
        name: "seahorse",
        aliases: &[],
        emoji: "🐠",
        source: Source::Commons("Hippocampus kuda"),
    },
    Animal {
        name: "clownfish",
        aliases: &[],
        emoji: "🐠",
        source: Source::Commons("Amphiprion ocellaris"),
    },
    Animal {
        name: "goldfish",
        aliases: &[],
        emoji: "🐟",
        source: Source::Commons("Carassius auratus"),
    },
    Animal {
        name: "sugar glider",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Petaurus breviceps"),
    },
    Animal {
        name: "manatee",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Trichechus manatus"),
    },
    Animal {
        name: "narwhal",
        aliases: &[],
        emoji: "🐋",
        source: Source::Commons("Monodon monoceros"),
    },
    Animal {
        name: "hyena",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Crocuta crocuta"),
    },
    Animal {
        name: "wolverine",
        aliases: &[],
        emoji: "🐾",
        source: Source::Commons("Gulo gulo"),
    },
];
